### PR TITLE
cmake compiler settings & logger improvement

### PR DESCRIPTION
**Pull request by 333fps**
Hello Dustin,

The goal of this PR was first to make the SCION::LOGGER consistent accross platforms and compilers which is not the case due to the variadic macro '##__VA_ARGS__' not working when Args... are empty on some compilers... I also wanted to reduce the number of macros and #ifdef WIN32, #ifdef __linux etc when possible.
To achieve this, I did the following changes:

- Use of '__VA_OPT__' instead which is conforming with stdc++11 and newer. It is working well but MSVC compiler requires to have the flag /Zc:__cplusplus in the command line...

    * To make this PR worth it and achieve this commit, I felt it might be the time to give the ability to the user of those libraries to be able to tweak the compiler, enable/disable warnings, etc...
    * Added 'CompilerSettings.cmake' in the root/cmake/' directory, populated with standard compiler and linker options (including /Zc:__cplusplus) - called from root CMakeLists.txt.

    * To enable the compilers settings accross subprojects, the following must be included in every project CMakeLists.txt (already updated accross the SCION libraries):
        ````
        target_compile_options(<LIB_NAME> PRIVATE $<$<COMPILE_LANGUAGE:CXX>:${CXX_COMPILE_FLAGS}>)
        ````  

    * Added 'CMakeSettings.json' in the root directory to allow the user to choose the build type from Visual Studio when working with cmake projects (Debug build are usually very slow when playing with OpenGL). 'CMakeSettings.json'  is automatically parsed by Visual Studio like cmake script files:  
                    Capture

- Other:
    * Fixed an annoying warning in 'Logger.inl' where GCC was complaining about static std:string being a non-POD type.
    * Slightly updated README.md

### CODE REVIEW

**Comment by dwjclark11** [comment]
@333fps Hey Ronan, this is great. I did not know about Soil2. 
Approved.

**Comment by dwjclark11** [comment]
@333fps Hey Ronan, the only issue I just found after compiling the changes, I didn't notice in the review, was the change to the button (Play/Stop) colors in the scene display. Now both buttons can be green at the same time. 

image

No problem though, I will push I fix on my next commit. I have a couple coming as well. 

Thanks

**Comment by 333fps** [comment]
Hello Dustin,,
Sorry for that... just pushed a new PR to fix this. It's just a proposal, but I guess it safer to not rely on 'imgui_internal.h" which is a private api and not stable.

**Comment by dwjclark11** [comment]
@333fps Hey Ronan,
No problem at all, I appreciate all of the work and help that you are putting in. I do agree, the UI will become more sophisticated later on and it is better to not have to change ImGui if not needed. 

Thanks.

**Pull request merged**
