### PR TITLE
OpenGL debug callback & Laptops hybrid gpu bugfixes

### PR DESCRIPTION
**Pull request by 333fps**
Following this graphics bug:
image

 I went into the following which could be interesting at the end:

**PR**
New class:
- 	SCION_RENDERING:OpenGLDebugger
Allows realtime Hardware OpenGL debugging (almost like in Vulkan).
To enable this feature: open the ROOT/CMakeLists.txt and amend the following:
image

	- Options added:
Enable OpenGL realtime/synchronous break on error/warning
image
image
The last one is probably not usefull as this enables warnings for future depreciations...

New feature:
- 	Force OpenGL discrete gpu on optimus laptops
image

- Modifications:
	SCION_LOGGER: added method to log error without 'std::source_location' in case of '__debugbreak() [linux/windows]' called.

My laptop is fitted with Optimus hybrid GPU. The orignal bug appears when I run the app on Intel Arc integrated GPU (default) and disappears when running on nVidia discrete GPU thanks to the 'SCION_OPENGL_FORCE_DISCRETE_GPU' new option.

**Testing:**
With 'SCION_OPENGL_DEBUG_CALLBACK_FWD_COMPATIBILITY _ON_', this nice bug was logged in the console:
image

Enabling 'SCION_OPENGL_DEBUG_BREAKONERROR' gave me this thanks to visual studio callstack:
image

image

Checking the docs, it looks that glLineWidth cannot be >1.f when FWD_COMPATIBILITY_CONTEXT in enabled :)... not a big deal, but at least the debugger is working :)
So  I switched 'SCION_OPENGL_DEBUG_CALLBACK_FWD_COMPATIBILITY' back to OFF.	

**FILTERING**
For now, ignore list is located in 'Scion2D/SCION_RENDERING/src/OpenGLDebugger.cpp':
image

**CONCLUSION**
This PR is not related to the original bug but leads to two new features....

### CODE REVIEW

**Comment by dwjclark11** [comment]
@333fps This is a wonderful addition to the engine. It will definitely come in handy to other people having similar issues. The logger information is a great touch as well. Thanks!

Approved!!

**Comment by 333fps** [comment]
@dwjclark11 Indeed the glDebugMessageCallback introduced on OpenGL 4.3 is a pretty usefull one.

Sorry, I did not take time to update the 'README.md', also, for sake of consitency with the GL specification, I will have to remove or move the SCION_OPENGL_DEBUG_CALLBACK_FWD_COMPATIBILITY macro, This forces SDL to enable the WGL_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB before calling wglCreateContextAttribsARB for modern OpenGL creation. Thus it is not really related to debugging.

The purpose of WGL_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB is to create a 'pure' context removing depreciated functionalities and rising a warning/error for future depreciation/removal.

(Here WGL_ is for win32, on Linux/X)11, it would be GLX_)

glLineWidth being a depreciated function, this explains the error in my message above - with a 'pure' context, glLineWidth has no effect.

As you know, the ARB group did not remove any function since OpenGL 3.0, so OpenGL being stuck in version 4.6, there's no chance that those functions will be removed one day. But I like this flag which reflects good practices with the latests OpenGL standards and guidelines  - even if manufacturer are free to follow or not the Khronos group recommendations.

My own engine does not rely on external libs for windowing or graphics stuff. I just marked those functions with the c++14 [[deprecated]] flag to get a warning at compile time a long time ago.... so I was a bit rusty on it.

Also, I will need to add an additional check for a valid context before loading the callback otherwise it will crash at runtime - it's not enough to check OpenGL version > 4.3.

Thanks,

**Comment by dwjclark11** [comment]
@333fps Thank you for some more context of the changes and information. Your efforts are always appreciated! I have pulled the recent changes and they run perfectly for me. I like the new log messages that come with it as well. 

These are some things that I did not know about yet when it comes to graphics. I should start looking more into the standards and guidelines of open GL. 

Also, once the engine is "completed", I would like to pivot into another engine that will use vulkan and have 3D capabilities, but that will be a while before I get onto that. 

The next part of the series, we are going to be getting into file dialogs. In my original engine, I was doing everything using windows, so I just made some OS calls and they worked great; however, since we want the engine to have cross platform capabilities, I was thinking of using a library that does all that for us. 

For a couple of my projects, I used the https://github.com/btzy/nativefiledialog-extended, this is great because it handled everything I needed. The only issue was, I could not change the name of the dialog.

So, I am thinking of some different options currently on that one currently.

Thanks again for all the help and information!

**Comment by 333fps** [comment]
Hi,

nfd looks intersting, I'm not suprised about the dialog naming problem, as soon as you want to built a cross platform lib playing with native os api, it's almost impossible to keep it consistent.... (eg most file dialogs have no title on linux) what is an option for win32API is not for GTK3 or GTK4 or..., linux distros are free to implement their own fork of FOSS windowing libs etc.... I'm currently struggling a bit trying to implement some stuff with the same API for X11 and Wayland.... on my side, thanks to linux world, I prefer the X11 way of doing things (simple!), bot some have chosen Wayland to be the future(modern, incomplete documentation, dirty). Xorg time is running out now.

Of course for this immediate guis are more flexible... but if you want to stick to native wndows, you have to sacrify some options :( or to pull the whole Qt framework with its crazy licensing rules just to mimic it. 

I guess it's still possible to hook the process and hack the underlyng struct but that's a dirty way and probably not viable on the long run. (I'm not sure but I guess it was possible to change dialog titles with wxWidgets.).

Same goes if you want to have the same public api for a OpenGL+Vulkan engine.
Those are completely different.
My approach was to provide a very high level public API similar for both graphics specifications to make underlying OpenGL calls apparently working like the Vulkan ones. At the end the only difference for the final user is to do something like Engine::SetApi(Engine::Api::Vk) or Engine::SetApi(Engine Api::GL)  before to run the engine . Doing so, the whole construct will adapt silently to the chosen Api.
At the end, this is clean, but the workload was huge (years!). Of course, I still provide an opaque pointer (like glfw) to the underlying implementation that the user can cast to the graphic system and access/hook the native api.

Thanks for you work, it's very inspiring. As a solo hobbyist I really like your approach of doing things, without shortcuts and showing everything :). Thanks to you, I'm starting to like templating (which i always try to avoid caus' i'm a big fan of the pimpl idiom - hard to keep a clean api on multiplatform stuff otherwise).

Thanks,

**Comment by dwjclark11** [comment]
Hello @333fps,
Thank you so much for the kind words! I wish I had more time to do the content as well. I enjoy it a lot and it helps me grow as a developer. 

Having to redo the code I have already done, helps me find mistakes, and there are also some great contributors, such as yourself, that allow me to learn even more. 

I should probably use the Pimpl idiom more often than I do lol. 

I was thinking of maybe using the ImFileDialog as well. I am not sure yet. I will dabble a bit first and see which one I like to use more. I have already used nfd, so I will try out ImFileDialog, and others, this week sometime and see which one we should use going forward. 

I will be making a small video that proposes a new Challenge. The challenge is to create the RectFillTool. That should be out either today or tomorrow.

Thanks

**Comment by 333fps** [comment]
I'll try to find some time for this coming challenge :)

**Comment by dwjclark11** [comment]
Wonderful, it should be posted soon!

**Pull request merged**
